# Generated by Django 5.1.3 on 2024-12-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dse_topic",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Planet Earth"),
                            (2, "Microscopic World I"),
                            (3, "Metals"),
                            (4, "Acid and Bases"),
                            (5, "Fossil Fuels and Carbon Compounds"),
                            (6, "Microscopic World II"),
                            (7, "Redox Reactions, Chemical Cells and Electrolysis"),
                            (8, "Chemical Reactions and Energy"),
                            (9, "Rate of Reaction"),
                            (10, "Chemical Equilibrium"),
                            (11, "Chemistry of Carbon Compounds"),
                            (12, "Patterns in the Chemical World"),
                            (13, "Elective: Industrial Chemistry"),
                        ],
                        verbose_name="DSE syllabus",
                    ),
                ),
                (
                    "self_topic",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Microscopic World"),
                            (2, "Metals"),
                            (3, "Acid Base and Patterns in the Chemical World"),
                            (4, "Organic Chemistry"),
                            (5, "Redox Reactions"),
                            (6, "Reactions and Energy"),
                            (7, "Equilibrium and Rate of Reaction"),
                            (8, "Mole and Molar Volume"),
                            (9, "Elective: Industrial Chemistry"),
                        ],
                        verbose_name="Self-defined topic",
                    ),
                ),
                ("update_date", models.DateTimeField()),
                ("file", models.FileField(upload_to="notes")),
            ],
        ),
    ]
