# Generated by Django 5.1.3 on 2024-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="name",
            field=models.CharField(default="Alcohol", max_length=50),
            preserve_default=False,
        ),
    ]
